# Generated by Django 2.2.4 on 2019-08-28 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=15)),
                ('telefone', models.CharField(max_length=10)),
                ('celular', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=50)),
                ('dtnasc', models.DateField()),
                ('cpf', models.CharField(max_length=11)),
                ('rg', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('logradouro', models.CharField(max_length=80)),
                ('cep', models.CharField(max_length=8)),
                ('cidade', models.CharField(max_length=50)),
                ('uf', models.CharField(max_length=2)),
                ('idcliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Cliente')),
            ],
        ),
    ]
