# Generated by Django 2.2.4 on 2019-08-30 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco',
            old_name='logradouro',
            new_name='rua',
        ),
        migrations.AddField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(default='teste', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endereco',
            name='numero',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='endereco',
            name='idcliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='core.Cliente'),
        ),
    ]
