# Generated by Django 2.2.4 on 2019-08-31 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190830_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='idcliente',
            field=models.ForeignKey(db_column='idcliente', on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='core.Cliente'),
        ),
    ]
